### ISSUE TITLE
Generator ignores nullability

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/SwaggerProvider#178]
### Description

``` YAML
    Service:
      type: object
      properties:
        Услуга:
          type: string
        Стоимость:
          type: number
          format: ₴
          nullable: false
        Обязательная:
          type: boolean
          nullable: false
```

### Expected behavior

Properties of value type marked as `nullable: false` declared as non-nullable and has a non-nullable parameter in a constructor

### Actual behavior

`nullable: false` is ignored

### Related information 

1.0.0-Beta1
